language: ruby
rvm:
- 2.3.1
branches:
  only:
    - develop
    - staging
before_install:
- openssl aes-256-cbc -K $encrypted_79a87511fc7e_key -iv $encrypted_79a87511fc7e_iv -in deploy_key.enc -out deploy_key -d
script:
- gem install jekyll
- bash ./deploy.sh
