# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Paul'
tagline:          'tag line'
description:      'Random thoughts and ideas of a software developer.'
url:              http://www.pknopf.com/
baseurl:          /

paginate:         5

disqus_shortname: pknopf

github_user: pauldotknopf
github_repo_url: https://github.com/pauldotknopf/pauldotknopf.github.io/

exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'deploy_key', 'deploy_key.enc', 'compile.sh', 'deploy.sh']

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
