# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            pknopf
tagline:          'tag line'
description:      'This is the decrition'
url:              http://www.pknopf.com/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

disqus_shortname: pknopf

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
