# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Paul'
tagline:          'tag line'
description:      'Random thoughts and ideas of a software developer.'
url:              http://www.pknopf.com/
baseurl:          /

paginate:         5

disqus_shortname: pknopf

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
