baseURL = "https://www.pknopf.com/"
languageCode = "en-us"
title = "Paul Knopf"

theme = "beautifulhugo"

disqusShortname = "pauldotknopf"

[Author]
  name = "Paul Knopf"
  website = "https://pknopf.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3