baseURL = "https://www.pknopf.com/"
languageCode = "en-us"
title = "Paul Knopf"

theme = "beautifulhugo"

disqusShortname = "pknopf"

[Params]
  logo = "img/avatar-icon.png"
  comments = true

[Author]
  name = "Paul Knopf"
  website = "http://www.pknopf.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3